### ISSUE TITLE
[BUG] app not generated: punycode is deprecated.

### ISSUE THREAD

**Issue by ksbbf** [eXist-db/generator-exist#1117]
**Describe the bug**
> After the questionaire the generator ends with a DeprecationWarning. The app (or code) is not generated.

**To Reproduce**
> I am on macos, installed node via brew, yeoman via node, and the generator via node (2024-01-16).

**Logs, error messages**
> : the punycode Module is deprecated. Please use a userland alternative instead.
Error @existdb/exist
generator.run is not a function.

**Context (please always complete the following information):**
-   node version: `21.5.0` (corrected)
-   eXist-db version: `6.2.`
-   generator version: `recent`
-   install method: `npm`

**Comment by duncdrum** [comment]
@ksbbf Thanks for the bug report. I will take a look. the error hints at a problem with the `@exitdb/exist` package. Are you sure that you are using node version `10`?? That has been end of life for quite some time. Have you tried with a more recent (18 or 20) version of node?

**Comment by ksbbf** [comment]
> Are you sure that you are using node version `10`?? That has been end of life for quite some time. Have you tried with a more recent (18 or 20) version of node?

oh, sorry. you're right:
node version: 21.5.0
npm version: 10.2.4

**Comment by duncdrum** [comment]
@ksbbf so far I can"t reproduce the error the generator is running fine. What is the output `yo doctor` on your system?

**Comment by duncdrum** [comment]
I see a problem with `yo@5` in the meantime using `yo@4` works fine. I ll have to dig into the incompatibility with yeoman  v5. But that will take some time, as I have a rather full schedule atm.

**Comment by ksbbf** [comment]
@duncdrum Yes, that's a solution. I downgraded to yo@4 with

> npm uninstall yo
> npm install -g yo@4

After the questionaire several files were downloaded. the result looks like an existapp. (But there were several warnings)
I think, i can start from here. Thanks!

I believe we're done here.

**Comment by duncdrum** [comment]
the warnings are likely related to node v 21. these should go away soon, once I manage to do the upgrade to yo v 5. Thanks for the feedback
