### ISSUE TITLE
Documentation for build targets? sync?

### ISSUE THREAD

**Issue by cwittern** [eXist-db/generator-exist#113]
I recently discovered this and am now creating my first project. As the readme says there are build scripts created for automating dev tasks, I would be glad if the documentation could be a bit more detailed.  

What scripts for what purpose?  How are they invoked?  For example, when looking at .existdb-json I see that there seems to be enough information to invoke a sync command that would sync the project from the filesystem to the development server, but have no idea how to invoke such a sync.

**Comment by duncdrum** [comment]
Hello Christian,
`.existdb-json` is a file for enabling sync between the local filesystem and a running eXist instance in the atom editor via [atom-existdb](https://github.com/eXist-db/atom-existdb).
Depending on your choices the scaffold will have different scripts,  some run only once at app creation,  such. ass inserting your name into the license file header,  should you wish to change this at a later time you can do it manually or simply run the generator over an existing structure.  Others,  such as integrating xqtest into mocha and travis are self-maintaining meaning they keep doing their thing as your app grows.  

But yes the readme should be clearer,  thanks for reminding me that i wanted to include a bump version string function,  which I somehow forgot. 

Greetings
Duncan

**Comment by cwittern** [comment]
Hi Duncan,
Thanks for the clarification, I wonder how to do the equivalent from Emacs (currently also struggling with oXygen, which does not seem to like me, so maybe I should give atom a try:-)

**Comment by duncdrum** [comment]
assuming that you want to interface with the generator, two principal options come to mind (not knowing much about emacs and lisp). 
 *   use another js thingy such as [gulp-exist](https://github.com/eXist-db/gulp-exist)
 *   user the [rest-api](http://www.exist-db.org/exist/apps/doc/devguide_rest.xml) straight from lisp

oXygen uses a the xmlrcp api, which is older and has its quirks. Myself, i would go rest + multi-container docker service.
