### ISSUE TITLE
Issue with template teipub: Deutsches Textarchiv (dta)

### ISSUE THREAD

**Issue by lguariento** [eXist-db/generator-exist#139]
Pointing the browser to the index.html of an application generated with the teipub: Deutsches Textarchiv (dta) template returns this error:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<exception>
<path>/db/apps/editio/modules/view.xql</path>
<message>err:XPST0017 error found while loading module browse: Error while loading module lib/browse.xql: error found while loading module pages: Error while loading module pages.xql: error found while loading module pm-config: Error while loading module ../pm-config.xql: error found while loading module pm-latex: Error while loading module ../transform/dta-latex-module.xql: error found while loading module m: Error while loading module /db/apps/editio/transform/dta-latex.xql: Function latex:table() is not defined in namespace 'http://www.tei-c.org/tei-simple/xquery/functions/latex' [at line 413, column 21]
</message>
</exception>```

**Comment by joewiz** [comment]
Which version of generator-exist, eXist, and tei-publisher-lib?

**Comment by lguariento** [comment]
Ops... sorry.

eXist-db 5.0.0 RC4
OSX 10.11.6
TEI Publisher: Processing Model Libraries 2.5.0
generator-exist 1.0.1

**Comment by duncdrum** [comment]
hi luca can you check if the `repo.xml` has been copied into the the database?
There are a number of issues with the tei-publisher RC apps on 5.0.0-RC, only some are under my control. I might just remove the featured to create tei-publisher apps until the dust has settled.

**Comment by lguariento** [comment]
Yes, the repo.xml was copied anyway. I see it is now solved! Good.
