### ISSUE TITLE
Adopt community convention for library vs. main modules' file extensions

### ISSUE THREAD

**Issue by joewiz** [eXist-db/generator-exist#614]
**Is your feature request related to a problem? Please describe.**

We can help encourage use of the community convention for file extensions by making these the defaults for generated apps:

- main modules: `.xq`
- library modules: `.xqm`

(See the XQuery book, the XQuery for Humanists book, and discussions on exist-open and xquery-talk.)

**Describe the solution you'd like**

Template files should adopt these:

- app.xql -> app.xqm
- pre-install.xql -> pre-install.xq
- post-install.xql -> post-install.xq
- tests/xqs/test-suite.xql -> test-suite.xqm

The only one that can't change (at present) is controller.xql, which according to this logic should be controller.xq. However, the name of this file is [hardcoded in the eXist source](https://github.com/eXist-db/exist/blob/develop/exist-core/src/main/java/org/exist/http/urlrewrite/XQueryURLRewrite.java#L110).

I'd be happy to prepare a PR.

**Describe alternatives you've considered**

Perpetuation of current muddled state, in which file extensions for XQuery are effectively meaningless for the purpose of distinguishing between library and main modules.

**Additional context**

n/a

**Comment by duncdrum** [comment]
I ll have a look. This will be a breaking change, so I’ll try to roll it into next major version release.
