### ISSUE TITLE
[BUG] Building empty app without bootstrap modules writes bootstrap dependencies into build.xml

### ISSUE THREAD

**Issue by djbpitt** [eXist-db/generator-exist#729]
**Describe the bug**
I created a new exist-db app with the "empty" option. When I ran `ant` to build, it raised an error about:

```
BUILD FAILED
/Users/djb/repos/parse-xpath-app/build.xml:12: Warning: Could not find file /Users/djb/repos/parse-xpath-app/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js to copy.
```

I don't think there should be bootstrap dependencies when I create an empty app. When I comment out the four bootstrap dependencies in *build.xml*, the build succeeds. I think those dependencies should not have been created when yeoman generated the app skeleton.

**Expected behavior**
I expect the build to succeed without my editing *build.xml*.

**To Reproduce**
Create an empty app and run `ant`.

**Context (please always complete the following information):**
 - OS: macOS 11.5.2
 - eXist-db Version: 5.3
 - Java Version: 1.8.0_301
-  App Version: 0.0.1

**Additional context**
- How is eXist-db installed? DMG
- Any custom changes in e.g. `conf.xml`? No

**Comment by duncdrum** [comment]
I ll look into this. The default `empty` template is modeled after the one from exide with the same name, which did include bootstrap. But there have been more requests about a more minimal template. 

In each case the current template should build without errors.

**Comment by djbpitt** [comment]
Thanks, @duncdrum , for the quick response. I don't have a pre-5.3 version of eXist-db to check, but I do remember that the old eXide-based app-creation widget had options for a minimal (no Bootstrap) setup, an eXist-db setup, and something in between, which did use Bootstrap. It sounds as if your "empty" template follows that in-between version, but I am confident that there was an option in the eXide interface to initialize without Bootstrap because that's what I used to use regularly. Thank you for for being willing to look into a simpler initialization in your yeoman package!

**Comment by duncdrum** [comment]
@djbpitt yes so this was an oversight on my part.

the next release will no longer have this bug.

In the meantime: If you simply remove these four lines from the generated `build.xml` file all should be back to working. 

```xml
 <copy file="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js" todir="resources/scripts" />
    <copy file="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map" todir="resources/scripts" />
    <copy file="node_modules/bootstrap/dist/css/bootstrap.min.css" todir="resources/css" />
    <copy file="node_modules/bootstrap/dist/css/bootstrap.min.css.map" todir="resources/css" />
```

i'm not quite ready for the next release, but hope to finish working on it soon.

**Comment by djbpitt** [comment]
@duncdrum Thanks, Duncan!
